In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import numpy as np

In [2]:
img=cv2.imread('img.jpg')

In [3]:
img.shape

(165, 220, 3)

In [4]:
img[0].shape


(220, 3)

In [5]:
img[0][0].shape

(3,)

In [6]:
img[0][0]

array([164, 170, 159], dtype=uint8)

In [7]:
img[0]

array([[164, 170, 159],
       [169, 175, 164],
       [173, 179, 168],
       [174, 180, 169],
       [174, 180, 169],
       [177, 183, 172],
       [178, 184, 173],
       [178, 184, 173],
       [183, 189, 178],
       [179, 185, 174],
       [177, 183, 172],
       [181, 187, 176],
       [187, 193, 182],
       [190, 196, 185],
       [187, 193, 182],
       [183, 189, 178],
       [187, 191, 185],
       [188, 192, 186],
       [190, 194, 188],
       [192, 196, 190],
       [194, 198, 192],
       [197, 201, 195],
       [200, 204, 198],
       [202, 206, 200],
       [202, 206, 200],
       [199, 203, 197],
       [199, 203, 197],
       [203, 207, 201],
       [205, 209, 203],
       [204, 208, 202],
       [204, 208, 202],
       [205, 209, 203],
       [207, 211, 205],
       [200, 204, 198],
       [204, 208, 202],
       [208, 212, 206],
       [206, 210, 204],
       [208, 212, 206],
       [206, 210, 204],
       [192, 196, 190],
       [201, 205, 199],
       [206, 210

In [8]:
img

array([[[164, 170, 159],
        [169, 175, 164],
        [173, 179, 168],
        ...,
        [161, 167, 156],
        [154, 166, 154],
        [151, 165, 153]],

       [[168, 174, 163],
        [173, 179, 168],
        [177, 183, 172],
        ...,
        [165, 171, 160],
        [158, 170, 158],
        [154, 168, 156]],

       [[170, 176, 165],
        [175, 181, 170],
        [178, 184, 173],
        ...,
        [165, 173, 162],
        [160, 172, 160],
        [156, 170, 158]],

       ...,

       [[141, 146, 137],
        [145, 150, 141],
        [149, 154, 145],
        ...,
        [130, 127, 122],
        [126, 135, 125],
        [125, 139, 128]],

       [[139, 144, 135],
        [143, 148, 139],
        [147, 152, 143],
        ...,
        [132, 129, 124],
        [129, 138, 128],
        [127, 141, 130]],

       [[137, 144, 137],
        [140, 147, 140],
        [144, 151, 144],
        ...,
        [135, 132, 127],
        [132, 140, 133],
        [127, 142, 134]]

In [9]:
img.tofile('new.jpg')

In [10]:
new=cv2.imread('img.jpg',0)

In [11]:
new.shape

(165, 220)

In [12]:
new[0][0]

166

In [13]:
new[0]

array([166, 171, 175, 176, 176, 179, 180, 180, 185, 181, 179, 183, 189,
       192, 189, 185, 189, 190, 192, 194, 196, 199, 202, 204, 204, 201,
       201, 205, 207, 206, 206, 207, 209, 202, 206, 210, 208, 210, 208,
       194, 203, 208, 212, 211, 211, 212, 212, 210, 210, 210, 210, 210,
       210, 212, 213, 214, 208, 210, 214, 205, 201, 207, 206, 207, 203,
       213, 199, 204, 202, 203, 201, 205, 208, 207, 205, 204, 204, 205,
       206, 207, 205, 205, 204, 202, 202, 202, 200, 197, 197, 197, 196,
       196, 196, 196, 196, 196, 187, 188, 188, 188, 189, 190, 193, 195,
       195, 196, 195, 194, 195, 196, 194, 191, 188, 188, 189, 190, 191,
       192, 193, 193, 195, 196, 198, 198, 199, 199, 200, 201, 200, 201,
       203, 203, 203, 202, 202, 203, 205, 202, 199, 199, 202, 204, 203,
       201, 204, 207, 199, 205, 204, 197, 204, 200, 197, 203, 199, 201,
       200, 198, 202, 196, 194, 205, 199, 197, 199, 198, 199, 193, 196,
       197, 198, 197, 194, 192, 191, 192, 191, 190, 189, 188, 18

In [46]:
def makeColorImg(name='test.jpg',x=10,y=10,colour=tuple([0,0,0])):
    R,G,B=colour
    content=y*x*3
    IMG=np.zeros(content,dtype=int)
    i=0
    while(i<content):
        IMG[i]=np.random.randint(0,255)
        i+=1
        IMG[i]=np.random.randint(0,255)
        i+=1
        IMG[i]=np.random.randint(0,255)
        i+=1
    IMG=IMG.reshape(y,x,3)
    cv2.imwrite(name,IMG)
    #cv2.imshow('image',IMG)
    #cv2.waitKey()
    return IMG
    
    
    

In [50]:
IMG=makeColorImg('func.jpg',500,500,[255,180,255])